name: Build Droidian Kernel (Huawei Nova 3i)

on:
  push:
    branches: [ "droidian" ]
  pull_request:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Remove conflicting packages
        run: |
          sudo apt-get remove -y containerd containerd.io docker-ce docker-ce-cli docker.io runc || true
          sudo apt-get autoremove -y
          sudo apt-get clean
      
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      

      - name: Build in Docker
        run: |
          mkdir -p $HOME/droidian/packages
          docker run --rm \
            -v $HOME/droidian/packages:/buildd \
            -v ${{ github.workspace }}:/buildd/sources \
            quay.io/droidian/build-essential:current-amd64 \
            bash -c "
              set -xe
              apt-get update
              apt-get install -y linux-packaging-snippets
              cd /buildd/sources
              make -f debian/rules clean
              dpkg-buildpackage -us -uc -B
            "

      - name: List Build Artifacts
        run: ls -l $HOME/droidian/packages

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-debs
          path: $HOME/droidian/packages/*.deb
